#!/bin/bash

# ajouter dans rc.local Les droits en écriture sur le fichier + L'état par défaut
#    chmod a+w "/sys/class/leds/asus::kbd_backlight/brightness"
#    echo 3 > "/sys/class/leds/asus::kbd_backlight/brightness"
# NE PAS OUBLIER DE
# chmod a+x /usr/local/bin/asus-led
  
   
x=`cat "/sys/class/leds/asus::kbd_backlight/brightness"`
if [[ $1 = "down" && $x -ne 0 ]]; then
   let "x = x - 1"
elif [[ $1 = "up" && $x < 3 ]]; then
   let "x = x + 1"
fi
echo $x > "/sys/class/leds/asus::kbd_backlight/brightness"
